makerdao/next-gen-atlas

- A.1_Governance Scope/A.1_Governance Scope.md
revised Article Function Doc Type and instance
> Update A.1_Governance Scope.md

- A.1_Governance Scope/A.1_Governance Scope.json
> Update A.1_Governance Scope.json

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.makerdao.com/t/atlas-edit-weekly-cycle-proposal/25083
**Do not merge unless associated Governance Poll passes.**
> Atlas Edit Weekly Cycle Proposal 2024-09-16

- Sky Atlas/Sky Atlas.html
| Element | Source |
|--|--|
| [A.3.2.2.2.2 Dai Savings Rate](https://sky-atlas.powerhouse.io/#A.3.2.2.2.2_Dai_Savings_Rate_Current_Value-340dbe42-8453-49cb-9989-ce93d09f2462%7C57eab733e9510f53) | [Exec](https://vote.makerdao.com/executive/template-executive-vote-stability-scope-parameter-changes-lite-psm-usdc-a-phase-3-final-setup-aave-lido-market-spark-usds-ddm-activation-wbtc-legacy-vaults-parameter-changes-october-4-2024) |
| [A.3.2.2.3.2 USDS Spread](https://sky-atlas.powerhouse.io/#A.3.2.2.3.2_USDS_Spread_Current_Value-2503bed0-ff79-4af5-9c22-821409b5649c%7C57eab733e951bb59)| " |
| [A.3.8.1.1.1.6 WBTC-A](https://sky-atlas.powerhouse.io/#A.3.8.1.1.1.6_WBTC_A-1f5d7209-bd45-4746-b118-ce4861fe4ac6%7C57eaf45219bea3b44f2c) | " |
| [A.3.8.1.1.1.7 …
> Active element changes from October 4, 2024 exec

- Sky Atlas/Sky Atlas.html
DO NOT MERGE UNLESS POLL PASSES
TODO
> Update Sky Atlas for Oct 14 poll

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/weekly-atlas-edit-proposal-week-of-2024-10-21-0/25364
Do not merge unless associated Governance Poll passes.
> Atlas Edit Weekly Cycle Proposal - 2024-10-21

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/ad-recognition-submission-vigilant/20457/110
**Do not merge until signed message confirming offboarding is posted**
@VoteWizard
> Removing vigilant from Current Aligned Delegates

- Sky Atlas/Sky Atlas.html
> Active element update from October 17 2024 exec

- Sky Atlas/Sky Atlas.html
> Update of Available Funds in the Launch Project

- Sky Atlas/Sky Atlas.html
> AD contract update

- Sky Atlas/Sky Atlas.html
Changes from https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-week-of-2024-11-11-0/25507
> Atlas Weekly Edit Proposal for 2024-11-11

- Sky Atlas/Sky Atlas.html
Changes from: https://forum.sky.money/t/weekly-atlas-edit-proposal-week-of-2024-11-18-0/25552
Do not merge unless associated poll passes.
> Atlas Edit Weekly Cycle 2024-11-18

- Sky Atlas/Sky Atlas.html
> Active elements update from November 14, 2024 exec

- Sky Atlas/Sky Atlas.html
Ratifying exec: https://vote.makerdao.com/executive/template-executive-vote-out-of-schedule-executive-vote-stability-fee-changes-savings-rate-changes-december-6-2024
@boet1 , @CivicSage3
> Active elements update from December 6, 2024 OOS executive vote

- Sky Atlas/Sky Atlas.html
Actions changes from: http://forum.sky.money/t/spark-metamorpho-dai-vault-allocation/23987/78
> Update Sky Atlas.html

- Sky Atlas/Sky Atlas.html
Actions this post: https://forum.sky.money/t/derecognition-notice-for-multiple-aligned-delegates/25718
> remove derecognized delegates

- Sky Atlas/Sky Atlas.html
**Do not merge until January 9, 2025 Executive Vote passes**.
@boet1 , @VoteWizard
> Active elements update from January 9, 2025 Executive Vote

- Sky Atlas/Sky Atlas.html
> Launch Project budget update

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/cloaky-ad-recognition-submission/21082/103
@VoteWizard, @boet1
> Update Cloaky's EA address

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-for-week-of-february-17-2025/25979
**Do not merge unless associated poll passes**
@adamgfraser , @VoteWizard
> AE Weekly Cycle Proposal for week of February 17, 2025

- Sky Atlas/Sky Atlas.html
- Stability Fee 
- DAI Savings Rate
- Smart Burn Engine hop
- Onboard LBTC
- Onboard tBTC
- Onboard ezETH
- Onboard rsETH
@blimpa @VoteWizard
> 2025-03-20 executive changes

- Sky Atlas/Sky Atlas.html
@VoteWizard @0xldr @MakerJanSky @blimpa
> Add new AD aegisD

- Sky Atlas/Sky Atlas.html
Do not merge until executive executes
> April 3 spell updates

- Sky Atlas/Sky Atlas.html
@0xldr @MakerJanSky @VoteWizard
> New AD - Excel

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-week-of-april-7-2025/26232
**Do not merge unless associated poll passes**
> Atlas Edit Weekly Cycle Proposal for 2025-04-07

- Sky Atlas/Sky Atlas.html
Adds the update to the SBE logic that could not be included previously. This has already been voted on and approved:
https://vote.makerdao.com/polling/QmTNzwgn#poll-detail
> add SBE Splitter parameter modification update

- Sky Atlas/Sky Atlas.html
- Launch Project Funding
- Adjust cbBTC and tBTC Interest Rate Models
- Reduce WBTC Liquidation Threshold
> Update Sky Atlas

- Sky Atlas/Sky Atlas.html
Fixes the following:
- spelling errors/consistent wording
- orphaned tags
- duplicated tags
- indentation
- duplicate entries
- inconsistent naming of active data documents
> Fix typos and tags

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-week-of-april-21-2025/26291
**Do not merge unless associated poll passes**
> Atlas Edit Weekly Cycle Proposal for week of 2025-04-21

- Atlas Edit Proposals/AEP-10.md
- Atlas Edit Proposals/AEP-3.md
- Atlas Edit Proposals/AEP-8.md
Relevant polls, respectively:
- https://vote.makerdao.com/polling/QmXaoCeP
- https://vote.makerdao.com/polling/QmRgEcHV
- https://vote.makerdao.com/polling/QmRn24ab
@VoteWizard
> Status update for AEPs 3, 8, 10

- Sky Atlas/Sky Atlas.html
> New AD - Tango

- Sky Atlas/Sky Atlas.html
Originating forum post: https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-week-of-may-5-2025/26319
> Atlas Edit Weekly Cycle Proposal for the week of 2025-05-05

- Sky Atlas/Sky Atlas.html
Adds changes from https://forum.sky.money/t/atlas-edit-weekly-cycle-proposal-week-of-may-12-2025/26364
> add weekly edit proposal changes
